# Generated by Django 4.2.30 on 2026-06-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono Lucide', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud aproximada del municipio', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud aproximada del municipio', max_digits=9, null=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='businesses.provincia')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('provincia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ConsejoPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código identificador', max_length=20)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consejos_populares', to='businesses.municipio')),
            ],
            options={
                'verbose_name': 'Consejo Popular',
                'verbose_name_plural': 'Consejos Populares',
                'ordering': ['nombre'],
                'unique_together': {('municipio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud aproximada del barrio', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud aproximada del barrio', max_digits=9, null=True)),
                ('referencia', models.TextField(blank=True, help_text='Puntos de referencia cercanos', max_length=300)),
                ('consejo_popular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='businesses.consejopopular')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='businesses.municipio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('whatsapp', models.CharField(help_text='Número WhatsApp con código país', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud exacta del negocio', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud exacta del negocio', max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Max 1MB, WebP recomendado', null=True, upload_to='logos/')),
                ('activo', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.barrio')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='businesses.categoria')),
                ('consejo_popular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.consejopopular')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.municipio')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.provincia')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['slug'], name='businesses__slug_6141bd_idx'), models.Index(fields=['provincia', 'municipio'], name='businesses__provinc_ab9248_idx'), models.Index(fields=['categoria'], name='businesses__categor_ee5010_idx'), models.Index(fields=['activo'], name='businesses__activo_282e96_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='barrio',
            index=models.Index(fields=['municipio'], name='businesses__municip_c80b42_idx'),
        ),
        migrations.AddIndex(
            model_name='barrio',
            index=models.Index(fields=['consejo_popular'], name='businesses__consejo_b29c08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='barrio',
            unique_together={('municipio', 'nombre')},
        ),
    ]
